Practical implementation of Simple RNN


In [1]:
from tensorflow.keras.preprocessing.text import one_hot

I0000 00:00:1774955323.525990   31809 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1774955324.309008   31809 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1774955334.088103   31809 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
# define the vocabulary size 
voc_size = 10000

In [7]:
#One hot representation
one_hot_repre = [one_hot(words, voc_size)for words in sent]
one_hot_repre

[[7383, 209, 6212, 4384],
 [7383, 209, 6212, 3609],
 [7383, 1512, 6212, 2832],
 [227, 6378, 7472, 3392, 3791],
 [227, 6378, 7472, 3392, 7572],
 [1145, 7383, 3369, 6212, 3001],
 [6422, 343, 5841, 3392]]

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
sent_length = 8

In [10]:
import numpy as np

In [11]:
# here we use padding sequences in order to make all sentences of same size.
embedded_docs = pad_sequences(one_hot_repre, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7383  209 6212 4384]
 [   0    0    0    0 7383  209 6212 3609]
 [   0    0    0    0 7383 1512 6212 2832]
 [   0    0    0  227 6378 7472 3392 3791]
 [   0    0    0  227 6378 7472 3392 7572]
 [   0    0    0 1145 7383 3369 6212 3001]
 [   0    0    0    0 6422  343 5841 3392]]


In [12]:
## feature representation with dimension size of 10
dim = 10

In [13]:
from tensorflow.keras.layers import Input

In [14]:
model = Sequential()
# Move the shape definition here
model.add(Input(shape=(sent_length,))) 
# Remove input_length from here
model.add(Embedding(voc_size, dim)) 
model.compile(optimizer='adam', loss='mse')


E0000 00:00:1774955394.402305   31809 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step


array([[[ 0.01908961,  0.01538949, -0.03528502,  0.03267405,
          0.01691308,  0.01262477, -0.01833941, -0.0413442 ,
         -0.02286621,  0.04917804],
        [ 0.01908961,  0.01538949, -0.03528502,  0.03267405,
          0.01691308,  0.01262477, -0.01833941, -0.0413442 ,
         -0.02286621,  0.04917804],
        [ 0.01908961,  0.01538949, -0.03528502,  0.03267405,
          0.01691308,  0.01262477, -0.01833941, -0.0413442 ,
         -0.02286621,  0.04917804],
        [ 0.01908961,  0.01538949, -0.03528502,  0.03267405,
          0.01691308,  0.01262477, -0.01833941, -0.0413442 ,
         -0.02286621,  0.04917804],
        [ 0.03927575,  0.01968739,  0.00529951, -0.00390105,
          0.0034987 ,  0.01475273,  0.02095418,  0.02901237,
         -0.00681485,  0.03875614],
        [ 0.0163525 ,  0.01549398,  0.01536949,  0.03402353,
         -0.02455372,  0.00775527, -0.04832511, -0.04650197,
          0.04887496, -0.01984086],
        [-0.01386067,  0.03999784, -0.04258511,  0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 7383,  209, 6212, 4384], dtype=int32)