Practical implementation of Simple RNN


In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# define the vocabulary size 
voc_size = 10000

In [5]:
#One hot representation
one_hot_repre = [one_hot(words, voc_size)for words in sent]
one_hot_repre

[[4600, 5782, 594, 2523],
 [4600, 5782, 594, 5603],
 [4600, 891, 594, 8669],
 [2243, 3270, 2734, 5493, 4974],
 [2243, 3270, 2734, 5493, 9980],
 [5776, 4600, 8426, 594, 8240],
 [151, 4938, 5004, 5493]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
sent_length = 8

In [8]:
import numpy as np

In [9]:
# here we use padding sequences in order to make all sentences of same size.
embedded_docs = pad_sequences(one_hot_repre, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4600 5782  594 2523]
 [   0    0    0    0 4600 5782  594 5603]
 [   0    0    0    0 4600  891  594 8669]
 [   0    0    0 2243 3270 2734 5493 4974]
 [   0    0    0 2243 3270 2734 5493 9980]
 [   0    0    0 5776 4600 8426  594 8240]
 [   0    0    0    0  151 4938 5004 5493]]


In [10]:
## feature representation with dimension size of 10
dim = 10

In [11]:
from tensorflow.keras.layers import Input

In [12]:
model = Sequential()
# Move the shape definition here
model.add(Input(shape=(sent_length,))) 
# Remove input_length from here
model.add(Embedding(voc_size, dim)) 
model.compile(optimizer='adam', loss='mse')


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 276ms/step


array([[[-8.06987286e-04, -4.38349247e-02,  3.03910263e-02,
          3.36040966e-02,  2.03253292e-02, -3.96821499e-02,
         -2.37265117e-02,  3.17719914e-02, -4.00850922e-03,
          1.43483542e-02],
        [-8.06987286e-04, -4.38349247e-02,  3.03910263e-02,
          3.36040966e-02,  2.03253292e-02, -3.96821499e-02,
         -2.37265117e-02,  3.17719914e-02, -4.00850922e-03,
          1.43483542e-02],
        [-8.06987286e-04, -4.38349247e-02,  3.03910263e-02,
          3.36040966e-02,  2.03253292e-02, -3.96821499e-02,
         -2.37265117e-02,  3.17719914e-02, -4.00850922e-03,
          1.43483542e-02],
        [-8.06987286e-04, -4.38349247e-02,  3.03910263e-02,
          3.36040966e-02,  2.03253292e-02, -3.96821499e-02,
         -2.37265117e-02,  3.17719914e-02, -4.00850922e-03,
          1.43483542e-02],
        [ 2.09691785e-02, -7.57478178e-04,  3.90406698e-03,
          8.81157070e-03,  1.96191333e-02,  6.69417530e-03,
          3.06679718e-02, -2.21081134e-02,  2.789866

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 4600, 5782,  594, 2523])